port: 4000
host: 0.0.0.0
safe: false

### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
timezone: America/Sao_Paulo
lsi: false
markdown: kramdown
highlighter: pygments

### content configuration ###
title:       "Problema de Roteamento de Veículos"
keywords:    "Problema de Roteamento de Veículos"
description: "O Problema de Roteamento de Veículos Estático (Vehicle Routing Problem ou VRP) foi introduzido em 1959 por Dantzig e Ramser com o artigo “The Truck Dispatching Problem”, sendo um problema de otimização combinatorial difícil."
source_link: "https://vehicle-routing-problem.github.io/"
favicon:     #put a path like: "img/favicon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)

### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
